version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1800
      runas: ubuntu